### ISSUE TITLE
docker container connection reset by peer

### ISSUE THREAD

**Issue by Nachtmerrie** [opinkerfi/adagios#660]
Hello!

Both docker containers are broken. 

`opinkerfi/adagios-git` refuses to start. When `restart=Always` is added to the compose file it will be in a restart loop.

`opinkerfi/adagios-rpm` refuses to serve requests

```
curl http://0.0.0.0:8080
curl: (56) Recv failure: Connection reset by peer
```

No stdout/stderr on the containers and the logs directory is empty.

Compose file taken from the example with the addition of `restart: always`:
```yaml
version: '3.1'

services:
  adagios:
    image: opinkerfi/adagios-git:latest
    restart: always
    ports:
      - 8080:80
      - 6557:6557
    volumes:
      - ./adagios:/opt/adagios
      - ./pynag:/opt/pynag
      - ./logs:/var/log/nagios

volumes:
  adagios:
  pynag:
  logs:
```
